# Generated by Django 4.2.3 on 2024-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfanalysis',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
