# Generated by Django 4.2.3 on 2024-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfAnalysis', '0002_pdfanalysis_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfanalysis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
