# Generated by Django 4.2.3 on 2024-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfAnalysis', '0003_alter_pdfanalysis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfanalysis',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
