# Generated by Django 4.2.3 on 2024-08-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PdfAnalysis', '0004_alter_pdfanalysis_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfanalysis',
            old_name='maintainability',
            new_name='regulations',
        ),
    ]
