# Generated by Django 4.2.3 on 2024-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfAnalysis', '0005_rename_maintainability_pdfanalysis_regulations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfanalysis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
