# Generated by Django 4.2.3 on 2024-08-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='it_infrastructure',
            new_name='it',
        ),
    ]
