# Generated by Django 4.2.3 on 2024-08-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_primary_industry_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector_of_activity',
            field=models.JSONField(default=list),
        ),
    ]
